services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: true

    login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator

    AppBundle\Services\CountryProvider:
        class: AppBundle\Services\CountryProvider

    AppBundle\Interpreter\ManufacturerGroup:
        class: AppBundle\Interpreter\ManufacturerGroup

    app.default_price_system:
        class: Pimcore\Bundle\EcommerceFrameworkBundle\PriceSystem\AttributePriceSystem
        arguments:
            $options:
                attribute_name: price



    AppBundle\Security\LoginFormAuthenticator: '@login_form_authenticator'
    #AppBundle\Services\CountryProvider: '@country_provider'
    # Example custom templating helper
    # AppBundle\Templating\Helper\Example:
    #     # templating helpers need to be public as they
    #     # are fetched from the container on demand
    #     public: true
    #     tags:
    #         - { name: templating.helper, alias: fooBar }

    # Example event listener for objects
    # AppBundle\EventListener\TestListener:
    #     tags:
    #         - { name: kernel.event_listener, event: pimcore.dataobject.preUpdate, method: onObjectPreUpdate }
