<?php


namespace AppBundle\Model\Product;


class Cars extends \Pimcore\Model\DataObject\Cars
{
    public function getOSName()
    {
        parent::getOSName(); // TODO: Change the autogenerated stub
    }


    /**
     * @return string|null
     */
    public function getProductName() : ?string
    {
        return $this->getName();
    }
}
